allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@payloadcms/db-postgres@3.85.1'
  - '@payloadcms/drizzle@3.85.1'
  - '@payloadcms/graphql@3.85.1'
  - '@payloadcms/next@3.85.1'
  - '@payloadcms/richtext-lexical@3.85.1'
  - '@payloadcms/translations@3.85.1'
  - '@payloadcms/ui@3.85.1'
  - payload@3.85.1
  - '@payloadcms/live-preview-react@3.85.1'
  - '@payloadcms/live-preview@3.85.1'
  - '@payloadcms/plugin-multi-tenant@3.85.1'
